namespace NET_Thing_Encryptor
{
    partial class SettingsForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            rootLayout = new TableLayoutPanel();
            headerPanel = new Panel();
            labelHeaderSubtitleMuted = new Label();
            labelHeader = new Label();
            settingsPanel = new Panel();
            settingsLayout = new TableLayoutPanel();
            groupBoxStorage = new GroupBox();
            storageLayout = new TableLayoutPanel();
            labelSaveLocation = new Label();
            textBoxSaveLocation = new TextBox();
            buttonSaveLocation = new Button();
            labelImportLocation = new Label();
            textBoxImportLocation = new TextBox();
            buttonImportLocation = new Button();
            labelExportLocation = new Label();
            textBoxExportLocation = new TextBox();
            buttonExportLocation = new Button();
            groupBoxAppearance = new GroupBox();
            appearanceLayout = new TableLayoutPanel();
            checkBoxDarkMode = new CheckBox();
            labelDarkModeHintMuted = new Label();
            groupBoxSecurity = new GroupBox();
            securityLayout = new TableLayoutPanel();
            labelAutoLock = new Label();
            numericAutoLockMinutes = new NumericUpDown();
            labelAutoLockHintMuted = new Label();
            groupBoxImageViewer = new GroupBox();
            imageViewerLayout = new TableLayoutPanel();
            labelPreviousImageBuffer = new Label();
            numericPreviousImageBuffer = new NumericUpDown();
            labelNextImageBuffer = new Label();
            numericNextImageBuffer = new NumericUpDown();
            checkBoxRandomiseSelectedImage = new CheckBox();
            labelAutoplayInterval = new Label();
            numericAutoplaySeconds = new NumericUpDown();
            checkBoxLoopOnAutoplay = new CheckBox();
            footerPanel = new FlowLayoutPanel();
            buttonApply = new Button();
            buttonCancel = new Button();
            rootLayout.SuspendLayout();
            headerPanel.SuspendLayout();
            settingsPanel.SuspendLayout();
            settingsLayout.SuspendLayout();
            groupBoxStorage.SuspendLayout();
            storageLayout.SuspendLayout();
            groupBoxAppearance.SuspendLayout();
            appearanceLayout.SuspendLayout();
            groupBoxSecurity.SuspendLayout();
            securityLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numericAutoLockMinutes).BeginInit();
            groupBoxImageViewer.SuspendLayout();
            imageViewerLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numericPreviousImageBuffer).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numericNextImageBuffer).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numericAutoplaySeconds).BeginInit();
            footerPanel.SuspendLayout();
            SuspendLayout();
            rootLayout.ColumnCount = 1;
            rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            rootLayout.Controls.Add(headerPanel, 0, 0);
            rootLayout.Controls.Add(settingsPanel, 0, 1);
            rootLayout.Controls.Add(footerPanel, 0, 2);
            rootLayout.Dock = DockStyle.Fill;
            rootLayout.RowCount = 3;
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 76F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
            headerPanel.Controls.Add(labelHeaderSubtitleMuted);
            headerPanel.Controls.Add(labelHeader);
            headerPanel.Dock = DockStyle.Fill;
            headerPanel.Padding = new Padding(20, 12, 20, 8);
            headerPanel.Name = "headerPanel";
            labelHeader.AutoSize = true;
            labelHeader.Font = new Font("Segoe UI Semibold", 16F, FontStyle.Bold);
            labelHeader.Location = new Point(20, 10);
            labelHeader.Name = "labelHeader";
            labelHeader.Text = "Settings";
            labelHeaderSubtitleMuted.AutoSize = true;
            labelHeaderSubtitleMuted.Location = new Point(22, 47);
            labelHeaderSubtitleMuted.Name = "labelHeaderSubtitleMuted";
            labelHeaderSubtitleMuted.Text = "Storage, security and image viewer preferences";
            settingsPanel.AutoScroll = true;
            settingsPanel.Controls.Add(settingsLayout);
            settingsPanel.Dock = DockStyle.Fill;
            settingsPanel.Name = "settingsPanel";
            settingsPanel.Padding = new Padding(16, 6, 16, 12);
            settingsLayout.AutoSize = true;
            settingsLayout.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            settingsLayout.ColumnCount = 1;
            settingsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            settingsLayout.Controls.Add(groupBoxStorage, 0, 0);
            settingsLayout.Controls.Add(groupBoxAppearance, 0, 1);
            settingsLayout.Controls.Add(groupBoxSecurity, 0, 2);
            settingsLayout.Controls.Add(groupBoxImageViewer, 0, 3);
            settingsLayout.Dock = DockStyle.Top;
            settingsLayout.Name = "settingsLayout";
            settingsLayout.RowCount = 4;
            groupBoxStorage.AutoSize = true;
            groupBoxStorage.Controls.Add(storageLayout);
            groupBoxStorage.Dock = DockStyle.Top;
            groupBoxStorage.Margin = new Padding(0, 0, 0, 12);
            groupBoxStorage.Name = "groupBoxStorage";
            groupBoxStorage.Padding = new Padding(14, 10, 14, 14);
            groupBoxStorage.Text = "Storage";
            storageLayout.AutoSize = true;
            storageLayout.ColumnCount = 3;
            storageLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 190F));
            storageLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            storageLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 46F));
            storageLayout.Controls.Add(labelSaveLocation, 0, 0);
            storageLayout.Controls.Add(textBoxSaveLocation, 1, 0);
            storageLayout.Controls.Add(buttonSaveLocation, 2, 0);
            storageLayout.Controls.Add(labelImportLocation, 0, 1);
            storageLayout.Controls.Add(textBoxImportLocation, 1, 1);
            storageLayout.Controls.Add(buttonImportLocation, 2, 1);
            storageLayout.Controls.Add(labelExportLocation, 0, 2);
            storageLayout.Controls.Add(textBoxExportLocation, 1, 2);
            storageLayout.Controls.Add(buttonExportLocation, 2, 2);
            storageLayout.Dock = DockStyle.Fill;
            storageLayout.RowCount = 3;
            storageLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            storageLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            storageLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            labelSaveLocation.Anchor = AnchorStyles.Left;
            labelSaveLocation.AutoSize = true;
            labelSaveLocation.Text = "Encrypted data location";
            textBoxSaveLocation.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            textBoxSaveLocation.Name = "textBoxSaveLocation";
            buttonSaveLocation.Dock = DockStyle.Fill;
            buttonSaveLocation.Margin = new Padding(6, 4, 0, 4);
            buttonSaveLocation.Name = "buttonSaveLocation";
            buttonSaveLocation.Text = "…";
            buttonSaveLocation.Click += buttonSaveLocation_Click;
            labelImportLocation.Anchor = AnchorStyles.Left;
            labelImportLocation.AutoSize = true;
            labelImportLocation.Text = "Default import folder";
            textBoxImportLocation.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            textBoxImportLocation.Name = "textBoxImportLocation";
            buttonImportLocation.Dock = DockStyle.Fill;
            buttonImportLocation.Margin = new Padding(6, 4, 0, 4);
            buttonImportLocation.Name = "buttonImportLocation";
            buttonImportLocation.Text = "…";
            buttonImportLocation.Click += buttonImportLocation_Click;
            labelExportLocation.Anchor = AnchorStyles.Left;
            labelExportLocation.AutoSize = true;
            labelExportLocation.Text = "Default export folder";
            textBoxExportLocation.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            textBoxExportLocation.Name = "textBoxExportLocation";
            buttonExportLocation.Dock = DockStyle.Fill;
            buttonExportLocation.Margin = new Padding(6, 4, 0, 4);
            buttonExportLocation.Name = "buttonExportLocation";
            buttonExportLocation.Text = "…";
            buttonExportLocation.Click += buttonExportLocation_Click;
            groupBoxAppearance.AutoSize = true;
            groupBoxAppearance.Controls.Add(appearanceLayout);
            groupBoxAppearance.Dock = DockStyle.Top;
            groupBoxAppearance.Margin = new Padding(0, 0, 0, 12);
            groupBoxAppearance.Name = "groupBoxAppearance";
            groupBoxAppearance.Padding = new Padding(14, 10, 14, 14);
            groupBoxAppearance.Text = "Appearance";
            appearanceLayout.AutoSize = true;
            appearanceLayout.ColumnCount = 1;
            appearanceLayout.Controls.Add(checkBoxDarkMode, 0, 0);
            appearanceLayout.Controls.Add(labelDarkModeHintMuted, 0, 1);
            appearanceLayout.Dock = DockStyle.Fill;
            checkBoxDarkMode.AutoSize = true;
            checkBoxDarkMode.Name = "checkBoxDarkMode";
            checkBoxDarkMode.Text = "Use dark mode";
            checkBoxDarkMode.UseVisualStyleBackColor = true;
            labelDarkModeHintMuted.AutoSize = true;
            labelDarkModeHintMuted.Margin = new Padding(24, 3, 3, 0);
            labelDarkModeHintMuted.Name = "labelDarkModeHintMuted";
            labelDarkModeHintMuted.Text = "The new theme is applied after restarting the application.";
            groupBoxSecurity.AutoSize = true;
            groupBoxSecurity.Controls.Add(securityLayout);
            groupBoxSecurity.Dock = DockStyle.Top;
            groupBoxSecurity.Margin = new Padding(0, 0, 0, 12);
            groupBoxSecurity.Name = "groupBoxSecurity";
            groupBoxSecurity.Padding = new Padding(14, 10, 14, 14);
            groupBoxSecurity.Text = "Security";
            securityLayout.AutoSize = true;
            securityLayout.ColumnCount = 2;
            securityLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 260F));
            securityLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            securityLayout.Controls.Add(labelAutoLock, 0, 0);
            securityLayout.Controls.Add(numericAutoLockMinutes, 1, 0);
            securityLayout.Controls.Add(labelAutoLockHintMuted, 0, 1);
            securityLayout.SetColumnSpan(labelAutoLockHintMuted, 2);
            securityLayout.Dock = DockStyle.Fill;
            labelAutoLock.Anchor = AnchorStyles.Left;
            labelAutoLock.AutoSize = true;
            labelAutoLock.Text = "Automatically lock after (minutes)";
            numericAutoLockMinutes.Anchor = AnchorStyles.Left;
            numericAutoLockMinutes.Maximum = ThingRoot.MaximumAutoLockMinutes;
            numericAutoLockMinutes.Name = "numericAutoLockMinutes";
            numericAutoLockMinutes.Size = new Size(120, 30);
            labelAutoLockHintMuted.AutoSize = true;
            labelAutoLockHintMuted.Margin = new Padding(0, 5, 3, 0);
            labelAutoLockHintMuted.Name = "labelAutoLockHintMuted";
            labelAutoLockHintMuted.Text = "Set to 0 to disable automatic locking.";
            groupBoxImageViewer.AutoSize = true;
            groupBoxImageViewer.Controls.Add(imageViewerLayout);
            groupBoxImageViewer.Dock = DockStyle.Top;
            groupBoxImageViewer.Margin = new Padding(0);
            groupBoxImageViewer.Name = "groupBoxImageViewer";
            groupBoxImageViewer.Padding = new Padding(14, 10, 14, 14);
            groupBoxImageViewer.Text = "Image viewer";
            imageViewerLayout.AutoSize = true;
            imageViewerLayout.ColumnCount = 2;
            imageViewerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 260F));
            imageViewerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            imageViewerLayout.Controls.Add(labelPreviousImageBuffer, 0, 0);
            imageViewerLayout.Controls.Add(numericPreviousImageBuffer, 1, 0);
            imageViewerLayout.Controls.Add(labelNextImageBuffer, 0, 1);
            imageViewerLayout.Controls.Add(numericNextImageBuffer, 1, 1);
            imageViewerLayout.Controls.Add(checkBoxRandomiseSelectedImage, 0, 2);
            imageViewerLayout.SetColumnSpan(checkBoxRandomiseSelectedImage, 2);
            imageViewerLayout.Controls.Add(labelAutoplayInterval, 0, 3);
            imageViewerLayout.Controls.Add(numericAutoplaySeconds, 1, 3);
            imageViewerLayout.Controls.Add(checkBoxLoopOnAutoplay, 0, 4);
            imageViewerLayout.SetColumnSpan(checkBoxLoopOnAutoplay, 2);
            imageViewerLayout.Dock = DockStyle.Fill;
            imageViewerLayout.RowCount = 5;
            imageViewerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            imageViewerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            imageViewerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            imageViewerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            imageViewerLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            labelPreviousImageBuffer.Anchor = AnchorStyles.Left;
            labelPreviousImageBuffer.AutoSize = true;
            labelPreviousImageBuffer.Text = "Buffered previous images";
            numericPreviousImageBuffer.Anchor = AnchorStyles.Left;
            numericPreviousImageBuffer.Maximum = ThingRoot.MaximumImageViewerBufferCount;
            numericPreviousImageBuffer.Name = "numericPreviousImageBuffer";
            numericPreviousImageBuffer.Size = new Size(120, 30);
            numericPreviousImageBuffer.Value = 1;
            labelNextImageBuffer.Anchor = AnchorStyles.Left;
            labelNextImageBuffer.AutoSize = true;
            labelNextImageBuffer.Text = "Buffered next images";
            numericNextImageBuffer.Anchor = AnchorStyles.Left;
            numericNextImageBuffer.Maximum = ThingRoot.MaximumImageViewerBufferCount;
            numericNextImageBuffer.Name = "numericNextImageBuffer";
            numericNextImageBuffer.Size = new Size(120, 30);
            numericNextImageBuffer.Value = 2;
            checkBoxRandomiseSelectedImage.Anchor = AnchorStyles.Left;
            checkBoxRandomiseSelectedImage.AutoSize = true;
            checkBoxRandomiseSelectedImage.Name = "checkBoxRandomiseSelectedImage";
            checkBoxRandomiseSelectedImage.Text = "Include the selected image when randomising the order";
            checkBoxRandomiseSelectedImage.UseVisualStyleBackColor = true;
            labelAutoplayInterval.Anchor = AnchorStyles.Left;
            labelAutoplayInterval.AutoSize = true;
            labelAutoplayInterval.Text = "Autoplay interval (seconds)";
            numericAutoplaySeconds.Anchor = AnchorStyles.Left;
            numericAutoplaySeconds.Minimum = 1;
            numericAutoplaySeconds.Maximum = ThingRoot.MaximumAutoplayIntervalSeconds;
            numericAutoplaySeconds.Name = "numericAutoplaySeconds";
            numericAutoplaySeconds.Size = new Size(120, 30);
            numericAutoplaySeconds.Value = 5;
            checkBoxLoopOnAutoplay.Anchor = AnchorStyles.Left;
            checkBoxLoopOnAutoplay.AutoSize = true;
            checkBoxLoopOnAutoplay.Name = "checkBoxLoopOnAutoplay";
            checkBoxLoopOnAutoplay.Text = "Loop on Autoplay";
            checkBoxLoopOnAutoplay.UseVisualStyleBackColor = true;
            footerPanel.Controls.Add(buttonApply);
            footerPanel.Controls.Add(buttonCancel);
            footerPanel.Dock = DockStyle.Fill;
            footerPanel.FlowDirection = FlowDirection.RightToLeft;
            footerPanel.Name = "footerPanel";
            footerPanel.Padding = new Padding(16, 10, 16, 10);
            buttonApply.AutoSize = true;
            buttonApply.MinimumSize = new Size(100, 38);
            buttonApply.Name = "buttonApply";
            buttonApply.Text = "Apply";
            buttonApply.UseVisualStyleBackColor = true;
            buttonApply.Click += buttonApply_Click;
            buttonCancel.AutoSize = true;
            buttonCancel.DialogResult = DialogResult.Cancel;
            buttonCancel.MinimumSize = new Size(100, 38);
            buttonCancel.Name = "buttonCancel";
            buttonCancel.Text = "Cancel";
            buttonCancel.UseVisualStyleBackColor = true;
            buttonCancel.Click += buttonCancel_Click;
            AcceptButton = buttonApply;
            AutoScaleDimensions = new SizeF(10F, 25F);
            AutoScaleMode = AutoScaleMode.Font;
            CancelButton = buttonCancel;
            ClientSize = new Size(850, 720);
            Controls.Add(rootLayout);
            MinimumSize = new Size(720, 600);
            Name = "SettingsForm";
            ShowIcon = false;
            StartPosition = FormStartPosition.CenterParent;
            Text = "Settings";
            Load += SettingsForm_Load;
            rootLayout.ResumeLayout(false);
            headerPanel.ResumeLayout(false);
            headerPanel.PerformLayout();
            settingsPanel.ResumeLayout(false);
            settingsPanel.PerformLayout();
            settingsLayout.ResumeLayout(false);
            settingsLayout.PerformLayout();
            groupBoxStorage.ResumeLayout(false);
            groupBoxStorage.PerformLayout();
            storageLayout.ResumeLayout(false);
            storageLayout.PerformLayout();
            groupBoxAppearance.ResumeLayout(false);
            groupBoxAppearance.PerformLayout();
            appearanceLayout.ResumeLayout(false);
            appearanceLayout.PerformLayout();
            groupBoxSecurity.ResumeLayout(false);
            groupBoxSecurity.PerformLayout();
            securityLayout.ResumeLayout(false);
            securityLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numericAutoLockMinutes).EndInit();
            groupBoxImageViewer.ResumeLayout(false);
            groupBoxImageViewer.PerformLayout();
            imageViewerLayout.ResumeLayout(false);
            imageViewerLayout.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numericPreviousImageBuffer).EndInit();
            ((System.ComponentModel.ISupportInitialize)numericNextImageBuffer).EndInit();
            ((System.ComponentModel.ISupportInitialize)numericAutoplaySeconds).EndInit();
            footerPanel.ResumeLayout(false);
            footerPanel.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private TableLayoutPanel rootLayout;
        private Panel headerPanel;
        private Label labelHeader;
        private Label labelHeaderSubtitleMuted;
        private Panel settingsPanel;
        private TableLayoutPanel settingsLayout;
        private GroupBox groupBoxStorage;
        private TableLayoutPanel storageLayout;
        private Label labelSaveLocation;
        private TextBox textBoxSaveLocation;
        private Button buttonSaveLocation;
        private Label labelImportLocation;
        private TextBox textBoxImportLocation;
        private Button buttonImportLocation;
        private Label labelExportLocation;
        private TextBox textBoxExportLocation;
        private Button buttonExportLocation;
        private GroupBox groupBoxAppearance;
        private TableLayoutPanel appearanceLayout;
        private CheckBox checkBoxDarkMode;
        private Label labelDarkModeHintMuted;
        private GroupBox groupBoxSecurity;
        private TableLayoutPanel securityLayout;
        private Label labelAutoLock;
        private NumericUpDown numericAutoLockMinutes;
        private Label labelAutoLockHintMuted;
        private GroupBox groupBoxImageViewer;
        private TableLayoutPanel imageViewerLayout;
        private Label labelPreviousImageBuffer;
        private NumericUpDown numericPreviousImageBuffer;
        private Label labelNextImageBuffer;
        private NumericUpDown numericNextImageBuffer;
        private CheckBox checkBoxRandomiseSelectedImage;
        private Label labelAutoplayInterval;
        private NumericUpDown numericAutoplaySeconds;
        private CheckBox checkBoxLoopOnAutoplay;
        private FlowLayoutPanel footerPanel;
        private Button buttonApply;
        private Button buttonCancel;
    }
}
